site_name: MetaGF
theme:
  name: material
  palette: 
    primary: grey
nav:
  - index.md
  - reference/metagf/intde.md
  - reference/metagf/momi.md
  - reference/metagf/sommerfeld.md
  - reference/metagf/toms468.md
  - demo.md
  - refs.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/refs.bib"
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - src/metagf
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# plugins
# https://github.com/shyamd/mkdocs-bibtex
# https://squidfunk.github.io/mkdocs-material/reference/mathjax/
# https://mkdocstrings.github.io/usage/
# https://github.com/oprypin/mkdocs-gen-files