name: Build Docs 
on:
  push:
    branches:
      - main
      - adding-tooling
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python3 -m pip install flit
      - run: python3 -m flit install --deps production --extras doc
      - run: mkdocs gh-deploy --force
